# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install autopep8 pytest
        python3 -m pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
        if [ -f requirements.txt ]; then python3 -m pip install -r requirements.txt; fi
    - name: Lint with autopep8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        echo " linting with autopep8"
        autopep8 --inp-place --recursive . --aggressive --aggressive --verbose
        echo " linting complete......."
    - name: Test with pytest
      run: |
        echo "testing with pytest"
        pytest
